application/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from application import views

app_name = "application"

urlpatterns = [
    url(r"dbinfo/$", views.DBInfo.as_view(), name="dbinfo"),
    url(r"dbinfo/tbspace/$", views.tbspace_chart.as_view(), name="tbspace"),
    url(r"dbinfo/sga/$", views.sga_chart.as_view(), name="sga"),
    url(r"dbinfo/pga/$", views.pga_chart.as_view(), name="pga"),
    url(r"dbinfo/dbsize/$", views.dbsize_chart.as_view(), name="dbsize"),
    url(r"dbinfo/session/$", views.session_chart.as_view(), name="session"),

    url(r"RatioInfo/$", views.Ratio.as_view(), name="ratio"),

    url(r"Perf/$", views.Perf.as_view(), name="perf"),

]

dbmon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from dbmon import views



urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^application/", include("application.urls", namespace="application")),
    url(r"^manage/", include("manage_setting.urls", namespace="manage")),
    


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

application/models.py
from django.db import models

# Create your models here.

application/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, render_to_response
from django.contrib.auth.decorators import login_required


from accounts.models import company_admin, company_user

import pandas as pd
import datetime, time
import math

from db import MyMongo
from pexcept import PrintException

######## parent class ##########
class DashBoard_View(LoginRequiredMixin, TemplateView):
    template_name = ''

    def get(self, request, **kwargs):
        self.principal = False
        company_list = []
        if request.user.is_authenticated:
            user_id=request.user.id
            self.superuser=request.user.is_superuser
            if self.superuser == 0:
                company_id = company_user.objects.get(user_id=user_id).company_admin_id
                company_admin_ob = company_admin.objects.get(id=company_id)
                self.cid = company_admin_ob.company_id
                try:
                    if company_admin_ob.principal_id == user_id:
                        self.principal = True
                except Exception as e:
                    print(e)
            else:
                company_ip = ''
                self.company_list = company_admin.objects.all()

                if request.POST.get('company', '')!='':
                    request.session['company']=request.POST.get('company', '')
                try:
                    self.cid=request.session['company']
                except Exception as e:
                    print(e)
                    request.session['company']=self.company_list[0].company_id
                    self.cid=request.session['company']


        if request.GET.get('date1', '')!='':
            request.session['date1'] = request.GET.get('date1', '')
        else:
            request.session['date1'] = str(datetime.date.today()-datetime.timedelta(days=3))#-datetime.timedelta(days=7))
        if request.GET.get('date2', '')!='':
            request.session['date2'] = request.GET.get('date2', '')
        else:
            request.session['date2'] = str(datetime.date.today())

        self.temp = request.session['temp']
        self.date1 = request.session['date1']
        self.date2 = request.session['date2']
        self.dbname = 'cid_'+str(self.cid)



        try:
            with MyMongo(database=self.dbname) as conn:
                self.host_list = conn.query_one('dbmon_Dbinfo', 'host_name')

            if request.GET.get('host', '')!='': request.session['host'] = request.GET.get('host', '')
            else: request.session['host'] = self.host_list[0]
            self.host = request.session['host']

        except:
            PrintException()

    def post(self, request, **kwargs):
        return self.get(request, **kwargs)


class Chart_View(LoginRequiredMixin, TemplateView):
    template_name = ''

    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            user_id=request.user.id
            superuser=request.user.is_superuser
            if superuser == 0:
                company_id = company_user.objects.get(user_id=user_id).company_admin_id
                company_admin_ob = company_admin.objects.get(id=company_id)
                company_ip = company_admin_ob.company_ip
                self.cid = company_admin_ob.company_id
                try:
                    if company_admin_ob.principal_id == user_id:
                        self.principal = True
                except Exception as e:
                    print(e)
            else:
                company_ip = ''
                company_list = company_admin.objects.all()
                if request.POST.get('company', '')!='':
                    request.session['company']=request.POST.get('company', '')
                try:
                    self.cid=request.session['company']

                except:
                    request.session['company']=company_list[0].company_id
                    self.cid=request.session['company']

            self.temp = request.session['temp']
            self.date1_f = datetime.datetime.strptime(request.session['date1'], '%Y-%m-%d')
            self.date2_f = datetime.datetime.strptime(request.session['date2'], '%Y-%m-%d')+datetime.timedelta(days=1)
            self.dbname = 'cid_'+str(self.cid)

######test info ########





# Create your views here.
################### dbinfo page #########################
################### dbinfo page ########################
class DBInfo(DashBoard_View):
    template_name = 'application/dbinfo/info.html'

    def get(self, request, **kwargs):
        super(DBInfo, self).get(request, **kwargs)
        principal = self.principal
        try:
            with MyMongo(database=self.dbname) as conn:
                dbinfo = conn.query_in('dbmon_Dbinfo', request.session['host'])
                cpucount = conn.query_in('dbmon_Cpucount', request.session['host'])
                memory = conn.query_in('dbmon_Tsm', request.session['host'])

        except Exception as e:
            PrintException()
            print(e)
        try:
            update_time = dbinfo[0]['datetime']
        except Exception as e:
            PrintException()
            print(e)
            dbinfo = ()
            cpucount = ()
            update_time = datetime.datetime.now()

        return render(request, self.template_name, locals())


######## tbspace chart #########
class tbspace_chart(Chart_View):
    template_name = 'application/dbinfo/tbspace.html'

    def get(self, request, **kwargs):
        super(tbspace_chart, self).get(request, **kwargs)
        tbname = 'dbmon_Tbspace'
        try:
            with MyMongo(database=self.dbname) as conn:
                find = conn.query_in(tbname, request.session['host'], self.date1_f, self.date2_f)

            df = pd.DataFrame(i for i in find).drop('timestamp', axis=1, errors='ignore')
            table = list(df['Tablespace'].unique())

            tbspace = {}
            tbspace_f = {}
            for i in table:
                tbspace[i] = df.loc[df['Tablespace']== i].drop('Tablespace', axis=1).values.tolist()
                tbspace_f[i] = df.loc[df['Tablespace']== i].drop('Tablespace', axis=1).values.tolist()[::6]


            update_time = tbspace['SYSTEM'][-1][0]
        except Exception as e:
            PrintException()
            print(e)
            update_time = datetime.datetime.now()

        return render(request, self.template_name, locals())

######## sga_pga chart #########
class sga_chart(Chart_View):
    template_name = 'application/dbinfo/sga.html'

    def get(self, request, **kwargs):
        super(sga_chart, self).get(request, **kwargs)
        tbname = 'dbmon_Sga'
        try:
            with MyMongo(database=self.dbname) as conn:
                sga = conn.query_in(tbname, request.session['host'], self.date1_f, self.date2_f)

            sga_df = pd.DataFrame(i for i in sga).drop('timestamp', axis=1, errors='ignore')
            sga_dict = sga_df.to_dict('record')
            update_time = sga_dict[-1]['datetime']


        except Exception as e:
            PrintException()
            print(e)
            sga_dict = []

        return render(request, self.template_name, locals())


######## pga chart #########
class pga_chart(Chart_View):
    template_name = 'application/dbinfo/pga.html'

    def get(self, request, **kwargs):
        super(pga_chart, self).get(request, **kwargs)
        tbname = 'dbmon_Pga'
        try:
            with MyMongo(database=self.dbname) as conn:
                pga = conn.query_in(tbname, request.session['host'], self.date1_f, self.date2_f)

            pga_df = pd.DataFrame(i for i in pga).drop('timestamp', axis=1, errors='ignore')
            pga_dict = pga_df.to_dict('record')
            update_time = pga_dict[-1]['datetime']

        except Exception as e:
            PrintException()
            print(e)
            pga_dict = []

        return render(request, self.template_name, locals())


######## sga_pga chart #########
class dbsize_chart(Chart_View):
    template_name = 'application/dbinfo/dbsize.html'

    def get(self, request, **kwargs):
        super(dbsize_chart,self).get(request, **kwargs)
        tbname = 'dbmon_Dbsize'
        try:
            with MyMongo(database=self.dbname) as conn:
                find = conn.query_in(tbname, request.session['host'], self.date1_f, self.date2_f)

            df = pd.DataFrame(i for i in find).drop('timestamp', axis=1, errors='ignore')

            dbsize = df.to_dict('record')
            dbsize = dbsize[::6]
            update_time = dbsize[-1]['datetime']

        except Exception as e:
            PrintException()
            print(e)
            dbsize = []

        return render(request, self.template_name, locals())


######## session chart #########
class session_chart(Chart_View):
    template_name = 'application/dbinfo/session.html'
    def get(self, request, **kwargs):
        super(session_chart, self).get(request, **kwargs)
        tbname = 'dbmon_Session'

        with MyMongo(database=self.dbname) as conn:
            find = conn.query_in(tbname, request.session['host'], self.date1_f, self.date2_f)

        df = pd.DataFrame(i for i in find).drop('timestamp', axis=1, errors='ignore')
        session = df.to_dict('record')


        return render(request, self.template_name, locals())

################### dbinfo page end  #########################





#################### ratio page ###############################
#################### ratio_hit page ##########################
class Ratio(DashBoard_View):
    template_name = 'application/ratio/ratio_page.html'

    def get(self, request, **kwargs):
        super(Ratio, self).get(request, **kwargs)
        principal = self.principal
        try:
            date1_f = datetime.datetime.strptime(request.session['date1'], '%Y-%m-%d')

application/templates/application/dbinfo/dbsize.html
{% load staticfiles %}
<script type="text/javascript" src="{% static "js/canvasjs.min.js" %}"></script>



<script type="text/javascript">
window.onload = function () {

    var chart = new CanvasJS.Chart("chartContainer",
  	{
  		theme: "theme1",
  		title:{
        text: "DBSIZE",
        fontFamily: "fantasy"
  		},
      animationEnabled: true,
      zoomEnabled:true,
      legend: {
            verticalAlign: "center",
            horizontalAlign: "right",
            cursor: "pointer",
            itemclick: function (e) {
                //console.log("legend click: " + e.dataPointIndex);
                //console.log(e);
                if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                    e.dataSeries.visible = false;
                } else {
                    e.dataSeries.visible = true;
                }

                e.chart.render();
            }
        },
        axisY:{
          gridColor: "#e3e3e3"
        },
        toolTip: {
          shared: true
        },
  		data: [
    		{
          showInLegend: true,
          color: 'blue',
          legendText: "{{i}}",
          toolTipContent:  "{label} - {y} MB",
          legendText: "DBSIZE",
    			dataPoints: [
            {% for i in dbsize %}
    				{  y: {{i.dbsize}}, label:'{{i.datetime}}'},
            {% endfor %}
    			]
    		},

  		]
  	});
    chart.render();
  }
  function openpage(e){
  console.log(e.dataPoint);
  var url = e.dataPoint.detail;
  var newwin = window.open();   //此行一定要如此書寫,否則失效
  newwin.location= url;   // url是 cgi 程式或者超連結 html
  }
</script>
<div class="row m-b-2">
    <div id="chartContainer" style="height: 250px; width: 100%;" ></div>

</div>

application/templates/application/dbinfo/info.html
{% extends 'base.html' %}
{% block title %} DBinFormation {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}


{% block content %}



    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="dashboard_graph">

          <div class="row x_title">
            <div class="col-md-3 pull-left">
              <h3>DB Information</h3>
            </div>

            <div class="col-md-9 pull right">
                  <form action="" method="get" enctype="multipart/form-data">
                      <div class="col-sm-3">
                      <label for="date1">起始日期</label>
                        <input id="date1" type="date" name="date1" placeholder="YYYY-MM-DD" value="{{self.date1}}" onchange="this.form.submit()">
                      </div>
                      <div class="col-sm-3">
                      <label for="date2">結束日期</label>
                        <input id="date2" type="date" name="date2" placeholder="YYYY-MM-DD" value="{{self.date2}}" onchange="this.form.submit()">
                      </div>
                      <div class="col-sm-2">
                          <select class="form-control" name="host" id="host">
                            {%for f in self.host_list%}
                            <option{%if self.host == f%} SELECTED{%endif%}>{{f}}</option>
                            {%endfor%}
                          </select>
                      </div>
                      <div class="col-sm-1">
                        <input type="submit" class="btn btn-info btn-sm" value="搜尋" />
                      </div>
                      <p class="text-right text-muted">更新時間：{{update_time}}</p>
                  </form>
            </div>

          </div>
          <div class="x_content">

            <div class="col-xs-9">
              <!-- Tab panes -->
              <div class="tab-content">
                <div class="tab-pane active" id="basic-r">
                  <p class="lead">BASIC</p>
                  <div class="col-xs-12">
                    <div class="col-xs-4">
                      {% for i in dbinfo %}
                      <h4><strong>DB ID :  {{i.dbid}} </strong></h4>
                      <h4><strong>DB name :   {{i.db_name}} </strong></h4>
                      <h4><strong>DB Mode :   {{i.open_mode}} </strong></h4>
                      <h4><strong>Log Mode :   {{i.log_mode}} </strong></h4>
                      <h4><strong>Character :   {{i.NLS_CHARACTERSET}} </strong></h4>
                      <h4><strong>Build ver :   {{i.build_ver}} </strong></h4>
                      {% endfor %}
                    </div>
                    <div class="col-xs-4">
                      {% for i in dbinfo %}
                      <h4><strong>Instance Number :   {{i.instance_number}} </strong></h4>
                      <h4><strong>Instance Name :  {{i.instance_name}} </strong></h4>
                      <h4><strong>Status :   {{i.status}} </strong></h4>
                      <h4><strong>Startup Time :   {{i.startup_time}} </strong></h4>
                      <h4><strong>Edition :   {{i.edition}} </strong></h4>
                      <h4><strong>Expire Date :   {{i.expire_date}} </strong></h4>
                      {% endfor %}
                    </div>
                    <div class="col-xs-4">
                      {% for i in dbinfo %}
                      <h4><strong>Host Name :   {{i.host_name}} </strong></h4>
                      <h4><strong>OS :  {{i.platform_name}} </strong></h4>
                      <h4><strong>CPU :   {{i.cpu_model}} </strong></h4>
                      <h4><strong>Limit user :   {{i.limit_user}} </strong></h4>
                      <h4><strong>Limit CPU :   {{i.limit_cpu}} </strong></h4>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="tab-pane" id="memory-r">
                  <p class="lead">Memory</p>
                  <div class="col-xs-12">
                    <div class="col-xs-4">
                      {% for i in memory %}
                      <h4><strong>Tibero Shared Memory :   {{i.TSM}} MB </strong></h4>
                      <h4><strong>Shared Cache Size :  {{i.shared_cache_size}} MB </strong></h4>
                      <h4><strong>Buffer Size :   {{i.buffer_size}} MB </strong></h4>
                      <h4><strong>Block Size :   {{i.DB_block}} K</strong></h4>
                      <h4><strong>Redo Log :   {{i.redo_log}} MB </strong></h4>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-xs-3">
              <!-- required for floating -->
              <!-- Nav tabs -->
              <ul class="nav nav-tabs tabs-right">
                <li class="active"><a href="#basic-r" data-toggle="tab">Basic Info</a>
                </li>
                <li><a href="#memory-r" data-toggle="tab">Memory Info</a>
                </li>
              </ul>
            </div>


          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>

  </br>


		<!-- <div class="col-sm-12" id="errorlog">
		  <div class="table-responsive">
		    <table class="table table-striped" class="scrollable" id="error_tb">
		      <thead>
		      <tr>
		        <th>DateTime</th>
		        <th>internet IP</th>
		        <th>intranet IP</th>
		        <th>Priority</th>
		        <th>Category</th>
		        <th>MessageID</th>
		        <th>Message</th>
		      </tr>
		      </thead>
		      <tbody>

		      </tbody>
		    </table>

		    <script>
		    $(document).ready(function() {
		          $('#error_tb').DataTable( {
		              dom: 'Bfrtip',
		              buttons: [
		                  'print'
		              ],
		              "order": [[ 0, "desc" ]]
		          } );
		      } );
		    </script>
		    </div>
		  </div>
		</div>-->

		<!-- <div class="page-content-toggle" id="page-content-wrapper">
		  <div class="container-fluid">  -->

		    <!-- 1st row -->
		    <div class="row">
		      <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>table_space</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
  		        <div class="x_content">
  		          <iframe src="{% url 'application:tbspace' %}" width="100%" height="400px" frameborder="0" scrolling="no">
  		            <p>Your browser does not support iframes.</p>
  		          </iframe>
  		        </div>
            </div>
		      </div>
		    </div>
		    <!-- /1st row -->
		    <!-- 2nd row -->
		    <div class="row m-b-6">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>DBSIZE</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a></li>
                      <li><a href="#">Settings 2</a></li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
              </div>
  		        <div class="x_content">
  		          <iframe src="{% url 'application:dbsize' %}" width="100%" height="300px" frameborder="0" scrolling="no">
  		            <p>Your browser does not support iframes.</p>
  		          </iframe>
		          </div>
            </div>
		      </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>session</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a></li>
                      <li><a href="#">Settings 2</a></li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
              </div>
  		        <div class="x_content">
		          <iframe src="{% url 'application:session' %}" width="100%" height="300px" frameborder="0" scrolling="no">
		            <p>Your browser does not support iframes.</p>
		          </iframe>
		        </div>
		      </div>
		    </div>
        </div>
		    <!-- /2nd row -->
		    <!-- 3rd row -->
		    <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>PGA</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a></li>
                      <li><a href="#">Settings 2</a></li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
              </div>
  		        <div class="x_content">
  		          <iframe src="{% url 'application:sga' %}" width="100%" height="400px" frameborder="0" scrolling="no">
  		            <p>Your browser does not support iframes.</p>
  		          </iframe>
		          </div>
            </div>
		      </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>PGA</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a></li>
                      <li><a href="#">Settings 2</a></li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
              </div>
  		        <div class="x_content">
		          <iframe src="{% url 'application:pga' %}" width="100%" height="400px" frameborder="0" scrolling="no">
		            <p>Your browser does not support iframes.</p>
		          </iframe>
		        </div>
		      </div>

  		    </div>
  		  </div>

    <!--</div>
  </div>-->

{% endblock %}

application/templates/application/dbinfo/pga.html
{% load staticfiles %}
<script type="text/javascript" src="{% static "js/canvasjs.min.js" %}"></script>



<script type="text/javascript">
window.onload = function () {

    var chart = new CanvasJS.Chart("chartContainer",
  	{
  		theme: "theme1",
  		title:{
        text: "PGA",
        fontFamily: "fantasy"
  		},
      toolTip: {
        shared: true
      },
      axisY:{
        gridColor: "#e3e3e3"
      },
      animationEnabled: true,
      zoomEnabled:true,
      legend: {
            verticalAlign: "center",
            horizontalAlign: "right",
            cursor: "pointer",
            itemclick: function (e) {
                //console.log("legend click: " + e.dataPointIndex);
                //console.log(e);
                if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                    e.dataSeries.visible = false;
                } else {
                    e.dataSeries.visible = true;
                }

                e.chart.render();
            }
        },
  		data: [
    		{
          type: "stackedArea100",
          showInLegend: true,
          toolTipContent:  "{label} - Free - {y} MB (Total:{total})",
          legendText: "Free",
    			dataPoints: [
            {% for i in pga_dict %}

    				{  y: {{i.pga_total}}-{{i.pga_used}}-{{i.pga_fixed}}, label:'{{i.datetime}}', total:'{{i.pga_total}}MB'},

            {% endfor %}
    			]
    		},
        {
          type: "stackedArea100",
          showInLegend: true,
          toolTipContent:  "{label} - Used - {y} MB",
          legendText: "Used",
    			dataPoints: [
            {% for i in pga_dict %}

    				{  y: {{i.pga_used}}, label:'{{i.datetime}}'},

            {% endfor %}
    			]
    		},
        {
          type: "stackedArea100",
          showInLegend: true,
          toolTipContent:  "{label} - Fixed - {y} MB",
          legendText: "Fixed",
    			dataPoints: [
            {% for i in pga_dict %}

    				{  y: {{i.pga_fixed}}, label:'{{i.datetime}}'},

            {% endfor %}
    			]
    		},

  		]
  	});
    chart.render();
  }
  function openpage(e){
  console.log(e.dataPoint);
  var url = e.dataPoint.detail;
  var newwin = window.open();   //此行一定要如此書寫,否則失效
  newwin.location= url;   // url是 cgi 程式或者超連結 html
  }
</script>
<div class="row m-b-2">
    <div id="chartContainer" style="height: 350px; width: 100%;" ></div>

</div>
<!-- <div>
{% for i,j in tbspace.items %}
  {% for k in j %}
  <p>{{k.5}}</p>
  <p>{{k.2}}</p>
  {% endfor %}
{% endfor %}
</dir> -->

application/templates/application/dbinfo/session.html
{% load staticfiles %}
<script type="text/javascript" src="{% static "js/canvasjs.min.js" %}"></script>



<script type="text/javascript">
window.onload = function () {

    var chart = new CanvasJS.Chart("chartContainer",
  	{
  		theme: "theme1",
  		title:{
        text: "Session",
        fontFamily: "fantasy"
  		},
      axisY:{
        gridColor: "#e3e3e3"
      },
      toolTip: {
        shared: true
      },

      animationEnabled: true,
      zoomEnabled:true,
      legend: {
            verticalAlign: "center",
            horizontalAlign: "right",
            cursor: "pointer",
            itemclick: function (e) {
                //console.log("legend click: " + e.dataPointIndex);
                //console.log(e);
                if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                    e.dataSeries.visible = false;
                } else {
                    e.dataSeries.visible = true;
                }

                e.chart.render();
            }
        },
  		data: [
    		{
          type: "line",
          showInLegend: true,
          legendText: "{{i}}",
          toolTipContent:  "{label} - {y}",
          legendText: "Total",
    			dataPoints: [
            {% for i in session %}
    				{  y: {{i.total}}, label:'{{i.datetime}}'},
            {% endfor %}
    			]
    		},
        {
          type: "line",
          showInLegend: true,
          legendText: "{{i}}",
          toolTipContent:  "{label} - {y}",
          legendText: "ready",
    			dataPoints: [
            {% for i in session %}
    				{  y: {{i.ready}}, label:'{{i.datetime}}'},
            {% endfor %}
    			]
    		},
        {
          type: "line",
          showInLegend: true,
          legendText: "{{i}}",
          toolTipContent:  "{label} - {y}",
          legendText: "running",
    			dataPoints: [
            {% for i in session %}
    				{  y: {{i.running}}, label:'{{i.datetime}}'},
            {% endfor %}
    			]
    		},


  		]
  	});
    chart.render();
  }
  function openpage(e){
  console.log(e.dataPoint);
  var url = e.dataPoint.detail;
  var newwin = window.open();   //此行一定要如此書寫,否則失效
  newwin.location= url;   // url是 cgi 程式或者超連結 html
  }
</script>
<div class="row m-b-2">
    <div id="chartContainer" style="height: 250px; width: 100%;" ></div>

</div>
<!-- <div>
{% for i,j in tbspace.items %}
  {% for k in j %}
  <p>{{k.5}}</p>
  <p>{{k.2}}</p>
  {% endfor %}
{% endfor %}
</dir> -->