accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts import views

app_name = "accounts"

urlpatterns = [
    url(r"^login/$", views.Signup.as_view(), name="login"),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    #url(r"signup/$", views.Signup.as_view(), name="signup"),
    url(r"verification/$", views.verification, name="verification"),
    url(r"forgot/$", views.forgot_password, name="forgot"),
    url(r"resetpsw/$", views.reset_password, name="resetpsw"),

    url(r"templogin/$", views.temp_login, name="templogin"),
]

application/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from application import views

app_name = "application"

urlpatterns = [
    url(r"dbinfo/$", views.DBInfo.as_view(), name="dbinfo"),
    url(r"dbinfo/tbspace/$", views.tbspace_chart.as_view(), name="tbspace"),
    url(r"dbinfo/sga/$", views.sga_chart.as_view(), name="sga"),
    url(r"dbinfo/pga/$", views.pga_chart.as_view(), name="pga"),
    url(r"dbinfo/dbsize/$", views.dbsize_chart.as_view(), name="dbsize"),
    url(r"dbinfo/session/$", views.session_chart.as_view(), name="session"),

    url(r"RatioInfo/$", views.Ratio.as_view(), name="ratio"),

    url(r"Perf/$", views.Perf.as_view(), name="perf"),

]

dbmon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from dbmon import views



urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^application/", include("application.urls", namespace="application")),
    url(r"^manage/", include("manage_setting.urls", namespace="manage")),
    


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manage_setting/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from manage_setting import views

app_name = "manage_setting"

urlpatterns = [
    url(r"company/$", views.user_manage, name='user_manage'),
    url(r"company/edit/$", views.company_edit, name='company_edit'),
    url(r"user/add/$", views.user_manage_add, name='user_add'),
    url(r"user/del/$", views.user_manage_del, name='user_del'),
    url(r"user/edit/$", views.user_manage_edit, name='user_edit'),

    url(r"machine/$", views.mc_manage, name='mc_manage'),
    url(r"machine/add/$", views.mc_manage_add, name='mc_add'),
    url(r"machine/edit/$", views.mc_manage_edit, name='mc_edit'),
    url(r"machine/del/$", views.mc_manage_del, name='mc_del'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>DBMoN! | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "top_navigation.html" %}
            </div>
          {% endblock top_navigation %}
          <div class="right_col" role="main">
          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}
          </div>

          {% block footer %}
            <footer>
              {% include "footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>
    {% endblock body %}
  </body>
</html>

templates/base_o.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <title>{% block title %}DBMon{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->


    <!-- <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> -->

    <!-- <link rel="stylesheet" href="{% static 'css/master.css'%}"> -->

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <script  language="JavaScript" type="text/javascript" src="{% static "js/jquery727.js" %}"></script>
    <script  language="JavaScript" type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script  language="JavaScript" type="text/javascript" src="{% static "js/jquery.dataTables.js" %}"></script>
    <script  language="JavaScript" type="text/javascript" src="{% static "js/dataTables.buttons.min.js" %}"></script>
    <script  language="JavaScript" type="text/javascript" src="{% static "js/buttons.print.min.js" %}"></script>
    <script  language="JavaScript" type="text/javascript" src="{% static "js/print.min.js" %}"></script>

    <link rel="stylesheet" href="{% static "css/admin.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.dataTables.min.css" %}">
    <link rel="stylesheet" href="{% static "css/buttons.dataTables.min.css" %}">
    <link rel="stylesheet" href="{% static "css/print.min.css" %}">


    <style>
        body{
            /*width:1600px;*/
            margin:60px auto;
        }
        .dropdown-submenu {
            position: relative;
        }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }
    </style>
    <script language="JavaScript" type="text/javascript">
      $(document).ready(function(){
        $('.dropdown-submenu a.test').on("click", function(e){
          $(this).next('ul').toggle();
          e.stopPropagation();
          e.preventDefault();
        });
      });

    </script>

  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">HomePage</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'application:dbinfo' %}"><span class="glyphicon glyphicon"></span>DbInfo</a></li>
            {%if principal%}
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">管理設定<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'manage_setting:user_manage' %}">使用者及公司設定</a></li>
                <!-- <li><a href="/greensys/setting/source/">來源設定</a></li>
                <li class="dropdown-submenu"><a class="test" href="#">警示設定<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/greensys/setting/alarm/">Syslog</a></li>
                    <li><a href="/greensys/setting/alarm_snmp/">SNMP</a></li>
                  </ul>
                </li>
                <li><a href="/greensys/setting/ipfilter/">過濾IP名單</a></li> -->
              </ul>
            </li>
            {%endif%}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Hi! {{request.user}}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/accounts/resetpsw/"><span class="glyphicon glyphicon-user"></span>修改密碼</a></li>
                  {%if superuser == 1%}
                  <li><a href="/greensys/gsldadmin/company/all/"><span class="glyphicon glyphicon-briefcase"></span>GSLD權限</a></li>
                  {%endif%}
                  <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-check"></span>Sign Up</a></li>
              <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
            {% endif %}
          </ul>
        </div>

      </div>
    </nav>



    <!-- <nav class='navbar mynav' role='navigation' id='navbar'>
      <div class="container">
        <a class='navbar-brand mynav' herf="{% url 'home' %}" class="btn btn-simple">DBMON</a>

        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a herf="{% url 'accounts:logout' %}">Log Out<</a></li>
          {% else %}

            <li><a herf="{% url 'accounts:login' %}" class="btn btn-simple">Log In</a></li>
            <li><a herf="/accounts/signup/" class="btn btn-simple">Sign Up</a></li>

          {% endif %}

        </ul>

      </div>
    </nav> -->

    <div class="container-fluid">
      {%block header%}
        <div class="page-header">
          <h1 class="text-success"><span style="font-family:Arial,cursive"><strong>DBMon</strong></span></h1>
        </div>
      {%endblock%}

      <div class="col-sm-12">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

templates/footer.html
<div class="pull-right">
  SIMPLTON - Based on Template by <a href="https://colorlib.com/wp/free-bootstrap-admin-dashboard-templates/">Colorlib</a>
</div>
<div class="clearfix"></div>

templates/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'home' %}" class="site_title"><i class="fa fa-spinner"></i> <span>DBMoN!</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <!-- <div class="profile_pic">
      <img src="/static/images/img.jpg" alt="..." class="img-circle profile_img">
    </div> -->
    <div class="profile_info">
      <span>Welcome,</span>
      <h1>{{request.user}}</h1>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Home </a>
        </li>
        <li><a><i class="fa fa-dashboard"></i> DashBoard <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'application:dbinfo' %}">DB Information</a></li>
            <li><a href="{% url 'application:ratio' %}">DB Hit Ratio</a></li>
            <li><a href="{% url 'application:perf' %}">OS Perf</a></li>
          </ul>
        </li>
        {% if principal %}
        {% if self.temp != '1' %}
        <li><a><i class="fa fa-cog"></i> Setting <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'manage_setting:user_manage' %}">User</a></li>
            <li><a href="{% url 'manage_setting:mc_manage' %}">Machine Report</a></li>

          </ul>
        </li>
        {% endif %}
        {% endif %}
        <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Other Functions <span class="label label-success pull-right">Coming Soon</span></a></li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    {% if principal %}
    {% if self.temp != '1' %}
    <a data-toggle="tooltip" data-placement="top" title="Settings" href="{% url 'manage_setting:user_manage' %}">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    {% endif %}
    {% endif %}
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'accounts:logout' %}">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>

templates/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <div class="col-sm-6" style="margin-left:450px; margin-top:15px">
      {%if self.superuser == 1%}
        <form action="" method="post" enctype="multipart/form-data">
          <div class="col-sm-2" >
          <label for="company">選擇公司</label>
          </div>
          <div class="col-sm-4" >
              {% csrf_token %}
              <select class="form-control" name="company" id="company" onchange="this.form.submit()">
                {%for f in self.company_list%}
                <option{%if self.cid == f.company_id%} SELECTED{%endif%} value={{f.company_id}}>{{f.company_name}}</option>
                {%endfor%}
              </select>
          </div>
        </form>
      {%endif%}
      </div>
      
      {% if request.user.is_authenticated %}
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          {{request.user}}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          
          {% if self.temp != '1' %}
          {% if principal %}
          <li>
            <a href="{% url 'manage_setting:user_manage' %}">
              <span>使用者及公司設定</span>
            </a>
          </li>
          {% endif %}
          <li><a href="{% url 'accounts:resetpsw' %}"></span>修改密碼</a></li>
          {% endif %}
          {%if superuser == 1%}
          <li><a href="/greensys/gsldadmin/company/all/"></span>GSLD權限</a></li>
          {%endif%}
          <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
        </ul>
      </li>
      {% else %}

        <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
      {% endif %}
       <li class="" ><a href="/"><span class="glyphicon glyphicon-th-large"></span> Entrance Page</a></li>
    </ul>


  </nav>
</div>