dbmon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from dbmon import views



urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^application/", include("application.urls", namespace="application")),
    url(r"^manage/", include("manage_setting.urls", namespace="manage")),
    


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manage_setting/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from manage_setting import views

app_name = "manage_setting"

urlpatterns = [
    url(r"company/$", views.user_manage, name='user_manage'),
    url(r"company/edit/$", views.company_edit, name='company_edit'),
    url(r"user/add/$", views.user_manage_add, name='user_add'),
    url(r"user/del/$", views.user_manage_del, name='user_del'),
    url(r"user/edit/$", views.user_manage_edit, name='user_edit'),

    url(r"machine/$", views.mc_manage, name='mc_manage'),
    url(r"machine/add/$", views.mc_manage_add, name='mc_add'),
    url(r"machine/edit/$", views.mc_manage_edit, name='mc_edit'),
    url(r"machine/del/$", views.mc_manage_del, name='mc_del'),
]

manage_setting/models.py
from django.db import models
from accounts.models import company_admin
from django.contrib.auth.models import User

import datetime

# Create your models here.

class machine_manage(models.Model):
    hostname = models.CharField(verbose_name='hostname', max_length=150, blank=True)
    ip = models.GenericIPAddressField(verbose_name='IP')
    company = models.ForeignKey(company_admin, verbose_name='公司')
    cpu_limit = models.IntegerField(verbose_name='cpu_limit', default=80, max_length=3)
    disk_percent = models.BooleanField(verbose_name='Disk Use Percentage', default=1)
    disk_limit = models.FloatField(verbose_name='disk_limit(GB)', default=10, max_length=4)
    report_time = models.TimeField(verbose_name='Make Report Time', default=datetime.time(0,0,0))
    line = models.BooleanField(verbose_name='Line通知', default=0)

    class Meta:
        db_table = 'manage_mc'
    def __str__(self):
        return self.hostname

manage_setting/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from django.contrib.auth.models import User


from accounts.models import company_user
from manage_setting.models import machine_manage

###########manage user############################
class UserInfoForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class UserLineForm(ModelForm):
    class Meta:
        model = company_user
        fields = ['line_user_id']
#################################################


####################manage machine##################
class MachineInfo(ModelForm):
    hostname = forms.CharField()


    class Meta:
        model = machine_manage
        fields = '__all__'
        widgets = {
            'report_time': forms.TimeInput(attrs={'type':'time'}),
        }

manage_setting/views.py
from django.shortcuts import render, render_to_response, HttpResponseRedirect, Http404, get_object_or_404
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django import forms

from accounts.models import company_admin, company_user
from manage_setting.models import machine_manage

from sendmail import sendmail
from db import MyMongo

# Create your views here.
# def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
#     return ''.join(random.choice(chars) for _ in range(size))

######## parent class ##########





#############################使用者管理###############################
@login_required
def user_manage(request):
    from accounts.models import company_user
    principal = False
    template_name = 'manage_setting/user/user_manage.html'
    if request.session['temp'] == '1':
        return HttpResponseRedirect('/?temp=1')
    if request.user.is_authenticated():
        user_id = request.user.id
        superuser=request.user.is_superuser
        try:
            company = company_admin.objects.get(principal=user_id)
            company_user = company_user.objects.filter(company_admin_id=company.id)
            cid = company.company_id
            #dbname = 'cid_%s'%str(cid).zfill(8)
            principal = True
        except Exception as e:
            print(e)
            raise Http404("Page does not exist")

    return render(request, template_name, locals())
################################################################

#############################新增使用者###############################
@login_required
def user_manage_add(request):
    from accounts.models import User_Verify, company_user
    from django.contrib.auth.forms import UserCreationForm
    from accounts.forms import UserRegForm

    import smtplib
    import string
    import random

    template_name = 'manage_setting/user/user_manage_add.html'
    principal = False


    if request.session['temp'] == '1':
        return HttpResponseRedirect('/?temp=1')

    if request.user.is_authenticated():
        user_id = request.user.id
        superuser=request.user.is_superuser
        try:
            company = company_admin.objects.get(principal=user_id)
            cid = company.company_id
            #dbname = 'cid_%s'%str(cid).zfill(8)
            principal = True
        except Exception as e:
            print(e)
            raise Http404("Page does not exist")

        ###提交表單
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            form1 = UserRegForm(request.POST)
            if form.is_valid() and form1.is_valid():
                form.save()
                username = request.POST.get('username','')
                first_name = request.POST.get('firstname', '')
                last_name = request.POST.get('lastname', '')
                email = request.POST.get('Email', '')
                is_active = '1'
                line = ''
                values = (username, first_name, last_name, email, is_active, line)
                #manage_setting_insert(dbname, 'auth_user', values)

                authuser = User.objects.get(username=username)
                authuser_id = authuser.id
                authuser.first_name=request.POST.get('firstname', '')
                authuser.last_name=request.POST.get('lastname', '')
                authuser.email=request.POST.get('Email', '')
                authuser.is_active=1
                authuser.save()

                companyuser = company_user.objects.create(username = username, company_admin_id = company.id, user_id = authuser_id)
                companyuser.save()

                captcha=id_generator()
                user_verify = User_Verify.objects.create(user_id=authuser_id, captcha=captcha, is_verify=0)
                user_verify.save()


                ###寄送驗證碼
                sendmail('Verification', 'Hello, '+authuser.username+'!\nEnter '+captcha+' to verify your account.\nThank you!\n', [authuser.email])

                return HttpResponseRedirect(reverse('manage_setting:user_manage'))
        else:
            form = UserCreationForm()
            form1 = UserRegForm()
    return render(request, template_name, locals())
################################################################

#############################編輯使用者###############################
@login_required
def user_manage_edit(request):
    from manage_setting.forms import UserInfoForm, UserLineForm
    #from manage_setting.manage_setting_sql import manage_setting_update,manage_setting_select_by_column
    template_name = 'manage_setting/user/user_manage_edit.html'

    if request.session['temp'] == '1':
        return HttpResponseRedirect('/?temp=1')

    if request.user.is_authenticated():
        user_id = request.user.id
        superuser=request.user.is_superuser
        try:
            company = company_admin.objects.get(principal=user_id)
            cid = company.company_id
            #dbname = 'cid_%s'%str(cid).zfill(8)
            principal = True
        except Exception as e:
            print(e)
            raise Http404("Page does not exist")

        if request.method == 'POST':
            if request.GET.get('username','')!='':
                username = request.GET.get('username','')
                user_edit = User.objects.get(username=username)
                company_user_id = company_user.objects.get(user__id = user_edit.id)
                form = UserInfoForm(request.POST, instance=user_edit)
                form1 = UserLineForm(request.POST, instance=company_user_id)
                if form.is_valid() and form1.is_valid():

                    id = User.objects.get(username=username)
                    # print(id.id)
                    username = request.POST.get('username','')
                    first_name = request.POST.get('first_name', '')
                    last_name = request.POST.get('last_name', '')
                    email = request.POST.get('Email', '')
                    line = request.POST.get('line_user_id')
                    is_active = '1'
                    values = (id, username, first_name, last_name, email, is_active, line)
                    User.objects.filter(id = id.id).update(id = id.id, username = username, first_name = first_name, last_name = last_name,
                                                                        email = email, is_active = is_active)
                    company_user.objects.filter(user_id = id.id).update(line_user_id = line)

                    #manage_setting_update(dbname, 'auth_user', values)
                    form.save()
                    form1.save()
                return HttpResponseRedirect(reverse('manage_setting:user_manage'))
        else:
            if request.GET.get('username','')!='':
                username = request.GET.get('username','')
                user_edit = User.objects.get(username=username)
                company_user_id = company_user.objects.get(user__id = user_edit.id)
                form = UserInfoForm(instance=user_edit)
                form1 = UserLineForm(instance=company_user_id)
    return render(request, template_name, locals())
################################################################

#############################刪除使用者###############################
@login_required
def user_manage_del(request):
    #from manage_setting.manage_setting_sql import manage_setting_delete_by_column

    if request.session['temp'] == '1':
        return HttpResponseRedirect('/?temp=1')

    if request.user.is_authenticated():
        user_id = request.user.id
        superuser=request.user.is_superuser
        try:
            company = company_admin.objects.get(principal=user_id)
            cid = company.company_id
            #dbname = 'cid_%s'%str(cid).zfill(8)
            principal = True
        except Exception as e:
            print(e)
            raise Http404("Page does not exist")

        if request.GET.get('username','')!='':
            username = request.GET.get('username', '')
            #manage_setting_delete_by_column(dbname, 'auth_user', 'username', username)
            username = request.GET.get('username','')
            user_del = User.objects.get(username=username)
            user_del.delete()

    return HttpResponseRedirect(reverse('manage_setting:user_manage'))
################################################################

#############################編輯公司資訊###############################
@login_required
def company_edit(request):
    from accounts.forms import CompanyAdminForm
    template_name = 'manage_setting/user/company_edit.html'

    if request.session['temp'] == '1':
        return HttpResponseRedirect('/?temp=1')

    if request.user.is_authenticated():
        user_id = request.user.id
        superuser=request.user.is_superuser
        try:
            company = company_admin.objects.get(principal=user_id)
            cid = company.company_id
            #dbname = 'cid_%s'%str(cid).zfill(8)
            principal = True
        except Exception as e:
            print(e)
            raise Http404('Page does not exist')

        if request.method == 'POST':
            form = CompanyAdminForm(request.POST, instance=company)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(reverse('manage_setting:user_manage'))
        else:
            form = CompanyAdminForm(instance=company)
            form.fields['date_expiration'].widget = forms.HiddenInput()
            form.fields['is_active'].widget = forms.HiddenInput()
            form.fields['company_id'].widget.attrs['readonly'] = True

    return render(request, template_name, locals())
################################################################



#############################使用者管理###############################
@login_required
def mc_manage(request):

    principal = False

manage_setting/templates/manage_setting/machine/mc_manage.html
{% extends 'base.html' %}

{% block title %} Machine Management {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}


{% block content %}
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="dashboard_graph">

			<div class="row x_title">
				<div class="col-md-4 pull-left">
					<h1>Machine Management</h1>
				</div>

			</div>
			<div class="x_content">


				<div class="col-sm-6">
					<div class="col-sm-3 " style="float:right">
					  <a href="{% url 'manage_setting:company_edit' %}"><input type='button' value='編輯公司資訊'></a>
					</div>
				  <h5><strong>公司名稱</strong>：{{company.company_name}}</h5>
				  <h5><strong>統編</strong>：{{company.company_id}}</h5>
				  <h5><strong>IP</strong>：{{company.company_ip}}</h5>
				  <h5><strong>IP2</strong>：{{company.company_ip2}}</h5>
				  <h5><strong>IP3</strong>：{{company.company_ip3}}</h5>
				  <h5><strong>電話/傳真</strong>：{{company.company_tel}} / {{company.company_fax}}</h5>
				  <h5><strong>地址</strong>：{{company.company_address}}</h5>
				  <h5><strong>有效期限</strong>：{{company.date_expiration}}</h5>
				  <h5><strong>使用中</strong>：{{company.is_active}}</h5>
				  <h5><strong>Line群組id</strong>：{{company.line_group_id}}</h5>
				</div>

				<div class="col-sm-12" id="errorlog">
				  <div class="table-responsive">
				    <table class="table table-striped" class="scrollable" id="user_tb">
				      <thead>
				      <tr>
				        <th><a href="{% url 'manage_setting:mc_add' %}"><input type='button' value='新增'></a></th>
				        <th>HostName</th>
				        <th>IP</th>
				        <th>CPU_limit</th>
				        <th>Disk_limit</th>
								<th>Disk Use Percentage</th>
                <th>Make Report Time</th>
								<th>Line Notify</th>
				      </tr>
				      </thead>
				      <tbody>
								{% for w in mc %}
				      <tr>
				        <td><a href="{% url 'manage_setting:mc_edit' %}?hostname={{w.hostname}}&ip={{w.ip}}"><input type='button' value='編輯'></a>
				        </br>
				        <a href="javascript:if (confirm('你確定要刪除\nHostName：{{w.hostname}}\nIP：{{w.ip}} 嗎?')) location.href='{% url 'manage_setting:mc_del' %}?hostname={{w.hostname}}&ip={{w.ip}}'"><input type='button' value='刪除'></a></td>
								<td>{{w.hostname}}</td>
								<td>{{w.ip}}</td>
								<td>{{w.cpu_limit}}</td>
								<td>{{w.disk_limit}}</td>
								<td>{% if w.disk_percent == 0%}OFF {% else %} ON {% endif %}</td>
                <td>{{w.report_time}}</td>
								<td>{% if w.line == 0%}OFF {% else %} ON {% endif %}</td>
				      </tr>
								{% endfor %}

				      </tbody>
				    </table>

				    <script>
				    $(document).ready(function() {
				          $('#user_tb').DataTable( {
				              dom: 'Bfrtip',
				              buttons: [
				                  'print'
				              ],
				              "order": [[ 1, "asc" ]]
				          } );
				      } );
				    </script>
				  </div>
				</div>

			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>

{% endblock %}

manage_setting/templates/manage_setting/machine/mc_manage_add.html
{% extends 'base.html' %}
{% block title %} Machine Management {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/normalize-css/normalize.css" rel="stylesheet">
  <link href="/static/vendors/ion.rangeSlider/css/ion.rangeSlider.css" rel="stylesheet">
  <link href="/static/vendors/ion.rangeSlider/css/ion.rangeSlider.skinFlat.css" rel="stylesheet">
  <!-- Bootstrap Colorpicker -->
  <link href="/static/vendors/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet">

  <link href="/static/vendors/cropper/dist/cropper.min.css" rel="stylesheet">
{% endblock stylesheets %}




{% block content %}
  <div class="col-sm-6">
    <div class="col-sm-12">

      <form action="" method="post">
        {% csrf_token %}
        <table>
          {% load bootstrap %}
          {{form|bootstrap}}

        </table>
        <input type="submit" class="btn btn-info btn-sm" value="確認" />
        <input type ="button" class="btn btn-info btn-sm" onclick="history.back()" value="取消"></input>
      </form>
    </div>
  </div>

{% endblock %}


{% block javascripts %}
  {{ block.super}}
  <!-- Ion.RangeSlider -->
  <script src="/static/vendors/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>
  <!-- Bootstrap Colorpicker -->
  <script src="/static/vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
  <!-- jquery.inputmask -->
  <script src="/static/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
  <!-- jQuery Knob -->
  <script src="/static/vendors/jquery-knob/dist/jquery.knob.min.js"></script>
  <!-- Cropper -->
  <script src="/static/vendors/cropper/dist/cropper.min.js"></script>
{% endblock javascripts %}

manage_setting/templates/manage_setting/machine/mc_manage_edit.html
{% extends 'base.html' %}
{% block title %} Machine Management {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/normalize-css/normalize.css" rel="stylesheet">
  <link href="/static/vendors/ion.rangeSlider/css/ion.rangeSlider.css" rel="stylesheet">
  <link href="/static/vendors/ion.rangeSlider/css/ion.rangeSlider.skinFlat.css" rel="stylesheet">
  <!-- Bootstrap Colorpicker -->
  <link href="/static/vendors/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet">

  <link href="/static/vendors/cropper/dist/cropper.min.css" rel="stylesheet">
{% endblock stylesheets %}




{% block content %}
  <div class="col-sm-6">
    <div class="col-sm-12">

      <form action="" method="post">
        {% csrf_token %}
        <table>
          {% load bootstrap %}
          {{form|bootstrap}}

        </table>
        <input type="submit" class="btn btn-info btn-sm" value="確認" />
        <input type ="button" class="btn btn-info btn-sm" onclick="history.back()" value="取消"></input>
      </form>
    </div>
  </div>

{% endblock %}


{% block javascripts %}
  {{ block.super}}
  <!-- Ion.RangeSlider -->
  <script src="/static/vendors/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>
  <!-- Bootstrap Colorpicker -->
  <script src="/static/vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
  <!-- jquery.inputmask -->
  <script src="/static/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
  <!-- jQuery Knob -->
  <script src="/static/vendors/jquery-knob/dist/jquery.knob.min.js"></script>
  <!-- Cropper -->
  <script src="/static/vendors/cropper/dist/cropper.min.js"></script>
{% endblock javascripts %}